# _*_ coding:utf-8 _*_
# @File  : initlize_table_scripts.py
# @Time  : 2020-07-27 13:12
# @Author: zizle

""" 创建数据库的脚本 """


from db.mysql_z import MySqlZ


with MySqlZ() as cursor:
    # 郑州商品交易所日行情数据库
    cursor.execute("CREATE TABLE IF NOT EXISTS `czce_daily` ("
                   "`id` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,"
                   "`date` VARCHAR(8) NOT NULL,"
                   "`create_date` DATETIME NOT NULL DEFAULT NOW(),"
                   "`variety_en` VARCHAR(32) NOT NULL,"
                   "`contract` VARCHAR (32) NOT NULL,"
                   "`pre_settlement` DECIMAL(15,6) DEFAULT 0,"
                   "`open_price` DECIMAL(15,6) DEFAULT 0,"
                   "`highest` DECIMAL(15,6) DEFAULT 0,"
                   "`lowest` DECIMAL(15,6) DEFAULT 0,"
                   "`close_price` DECIMAL(15,6) DEFAULT 0,"
                   "`settlement` DECIMAL(15,6) DEFAULT 0,"
                   "`zd_1` DECIMAL(15,6) DEFAULT 0,"
                   "`zd_2` DECIMAL(15,6) DEFAULT 0,"
                   "`trade_volume` INT(11) DEFAULT 0,"
                   "`empty_volume` INT(11) DEFAULT 0,"
                   "`increase_volume` INT(11) DEFAULT 0,"
                   "`trade_price` DECIMAL(15,6) DEFAULT 0,"
                   "`delivery_price` DECIMAL(15,6) DEFAULT 0"
                   ") DEFAULT CHARSET='utf8';")
    # 郑州商品交易所日持仓排名数据库
    cursor.execute("CREATE TABLE IF NOT EXISTS `czce_rank` ("
                   "`id` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,"
                   "`date` VARCHAR(8) NOT NULL,"
                   "`create_date` DATETIME NOT NULL DEFAULT NOW(),"
                   "`variety_en` VARCHAR(32) NOT NULL,"
                   "`contract` VARCHAR (32) NOT NULL,"
                   "`rank` INT(11) NOT NULL,"
                   "`trade_company` VARCHAR(16) DEFAULT '',"
                   "`trade` INT(11) DEFAULT 0,"
                   "`trade_increase` INT(11) DEFAULT 0,"
                   "`long_position_company` VARCHAR(16) DEFAULT '',"
                   "`long_position` INT(11) DEFAULT 0,"
                   "`long_position_increase` INT(11) DEFAULT 0,"
                   "`short_position_company` VARCHAR(16) DEFAULT '',"
                   "`short_position` INT(11) DEFAULT 0,"
                   "`short_position_increase` INT(11) DEFAULT 0"
                   ") DEFAULT CHARSET='utf8';")
    # 郑州商品交易所每日仓单数据库
    cursor.execute("CREATE TABLE IF NOT EXISTS `czce_receipt` ("
                   "`id` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,"
                   "`date` VARCHAR(8) NOT NULL,"
                   "`create_date` DATETIME NOT NULL DEFAULT NOW(),"
                   "`variety_en` VARCHAR(32) NOT NULL,"
                   "`warehouse` VARCHAR (32) NOT NULL,"
                   "`receipt` INT(11) DEFAULT NULL DEFAULT 0,"
                   "`receipt_increase` INT(11) DEFAULT NULL DEFAULT 0,"
                   "`premium_discount` INT(11) NOT NULL DEFAULT 0"
                   ") DEFAULT CHARSET='utf8';")
    # 上海期货交易所日行情数据库
    cursor.execute("CREATE TABLE IF NOT EXISTS `shfe_daily` ("
                   "`id` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,"
                   "`date` VARCHAR(8) NOT NULL,"
                   "`create_date` DATETIME NOT NULL DEFAULT NOW(),"
                   "`variety_en` VARCHAR(32) NOT NULL,"
                   "`contract` VARCHAR (32) NOT NULL,"
                   "`pre_settlement` DECIMAL(15,6) DEFAULT 0,"
                   "`open_price` DECIMAL(15,6) DEFAULT 0,"
                   "`highest` DECIMAL(15,6) DEFAULT 0,"
                   "`lowest` DECIMAL(15,6) DEFAULT 0,"
                   "`close_price` DECIMAL(15,6) DEFAULT 0,"
                   "`settlement` DECIMAL(15,6) DEFAULT 0,"
                   "`zd_1` DECIMAL(15,6) DEFAULT 0,"
                   "`zd_2` DECIMAL(15,6) DEFAULT 0,"
                   "`trade_volume` INT(11) DEFAULT 0,"
                   "`empty_volume` INT(11) DEFAULT 0,"
                   "`increase_volume` INT(11) DEFAULT 0"
                   ") DEFAULT CHARSET='utf8';")
    # 上海期货交易所日持仓排名数据库
    cursor.execute("CREATE TABLE IF NOT EXISTS `shfe_rank` ("
                   "`id` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,"
                   "`date` VARCHAR(8) NOT NULL,"
                   "`create_date` DATETIME NOT NULL DEFAULT NOW(),"
                   "`variety_en` VARCHAR(32) NOT NULL,"
                   "`contract` VARCHAR (32) NOT NULL,"
                   "`rank` INT(11) NOT NULL,"
                   "`trade_company` VARCHAR(16) DEFAULT '',"
                   "`trade` INT(11) DEFAULT 0,"
                   "`trade_increase` INT(11) DEFAULT 0,"
                   "`long_position_company` VARCHAR(16) DEFAULT '',"
                   "`long_position` INT(11) DEFAULT 0,"
                   "`long_position_increase` INT(11) DEFAULT 0,"
                   "`short_position_company` VARCHAR(16) DEFAULT '',"
                   "`short_position` INT(11) DEFAULT 0,"
                   "`short_position_increase` INT(11) DEFAULT 0"
                   ") DEFAULT CHARSET='utf8';")
    # 中国金融期货交易所日行情数据库
    cursor.execute("CREATE TABLE IF NOT EXISTS `cffex_daily` ("
                   "`id` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,"
                   "`date` VARCHAR(8) NOT NULL,"
                   "`create_date` DATETIME NOT NULL DEFAULT NOW(),"
                   "`variety_en` VARCHAR(32) NOT NULL,"
                   "`contract` VARCHAR (32) NOT NULL,"
                   "`open_price` DECIMAL(15,6) DEFAULT 0,"
                   "`highest` DECIMAL(15,6) DEFAULT 0,"
                   "`lowest` DECIMAL(15,6) DEFAULT 0,"
                   "`close_price` DECIMAL(15,6) DEFAULT 0,"
                   "`settlement` DECIMAL(15,6) DEFAULT 0,"
                   "`zd_1` DECIMAL(15,6) DEFAULT 0,"
                   "`zd_2` DECIMAL(15,6) DEFAULT 0,"
                   "`trade_volume` INT(11) DEFAULT 0,"
                   "`trade_price` DECIMAL(15,6) DEFAULT 0,"
                   "`empty_volume` INT(11) DEFAULT 0"
                   ") DEFAULT CHARSET='utf8';")
    # 中国金融期货交易所日持仓排名数据库
    cursor.execute("CREATE TABLE IF NOT EXISTS `cffex_rank` ("
                   "`id` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,"
                   "`date` VARCHAR(8) NOT NULL,"
                   "`create_date` DATETIME NOT NULL DEFAULT NOW(),"
                   "`variety_en` VARCHAR(32) NOT NULL,"
                   "`contract` VARCHAR (32) NOT NULL,"
                   "`rank` INT(11) NOT NULL,"
                   "`trade_company` VARCHAR(16) DEFAULT '',"
                   "`trade` INT(11) DEFAULT 0,"
                   "`trade_increase` INT(11) DEFAULT 0,"
                   "`long_position_company` VARCHAR(16) DEFAULT '',"
                   "`long_position` INT(11) DEFAULT 0,"
                   "`long_position_increase` INT(11) DEFAULT 0,"
                   "`short_position_company` VARCHAR(16) DEFAULT '',"
                   "`short_position` INT(11) DEFAULT 0,"
                   "`short_position_increase` INT(11) DEFAULT 0"
                   ") DEFAULT CHARSET='utf8';")
    # 大连商品交易所日行情数据库
    cursor.execute("CREATE TABLE IF NOT EXISTS `dce_daily` ("
                   "`id` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,"
                   "`date` VARCHAR(8) NOT NULL,"
                   "`create_date` DATETIME NOT NULL DEFAULT NOW(),"
                   "`variety_en` VARCHAR(32) NOT NULL,"
                   "`contract` VARCHAR (32) NOT NULL,"
                   "`pre_settlement` DECIMAL(15,6) DEFAULT 0,"
                   "`open_price` DECIMAL(15,6) DEFAULT 0,"
                   "`highest` DECIMAL(15,6) DEFAULT 0,"
                   "`lowest` DECIMAL(15,6) DEFAULT 0,"
                   "`close_price` DECIMAL(15,6) DEFAULT 0,"
                   "`settlement` DECIMAL(15,6) DEFAULT 0,"
                   "`zd_1` DECIMAL(15,6) DEFAULT 0,"
                   "`zd_2` DECIMAL(15,6) DEFAULT 0,"
                   "`trade_volume` INT(11) DEFAULT 0,"
                   "`empty_volume` INT(11) DEFAULT 0,"
                   "`increase_volume` INT(11) DEFAULT 0,"
                   "`trade_price` DECIMAL(15,6) DEFAULT 0"
                   ") DEFAULT CHARSET='utf8';")
    # 大连商品交易所日持仓排名数据库
    cursor.execute("CREATE TABLE IF NOT EXISTS `dce_rank` ("
                   "`id` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,"
                   "`date` VARCHAR(8) NOT NULL,"
                   "`create_date` DATETIME NOT NULL DEFAULT NOW(),"
                   "`variety_en` VARCHAR(32) NOT NULL,"
                   "`contract` VARCHAR (32) NOT NULL,"
                   "`rank` INT(11) NOT NULL,"
                   "`trade_company` VARCHAR(16) DEFAULT '',"
                   "`trade` INT(11) DEFAULT 0,"
                   "`trade_increase` INT(11) DEFAULT 0,"
                   "`long_position_company` VARCHAR(16) DEFAULT '',"
                   "`long_position` INT(11) DEFAULT 0,"
                   "`long_position_increase` INT(11) DEFAULT 0,"
                   "`short_position_company` VARCHAR(16) DEFAULT '',"
                   "`short_position` INT(11) DEFAULT 0,"
                   "`short_position_increase` INT(11) DEFAULT 0"
                   ") DEFAULT CHARSET='utf8';")
